codon_types = {
    # Hydrophobic
    'GCU': 'Hydrophobic',
    'GCC': 'Hydrophobic',
    'GCA': 'Hydrophobic',
    'GCG': 'Hydrophobic',
    'GUU': 'Hydrophobic',
    'GUC': 'Hydrophobic',
    'GUA': 'Hydrophobic',
    'GUG': 'Hydrophobic',
    'UUA': 'Hydrophobic',
    'UUG': 'Hydrophobic',
    'CUU': 'Hydrophobic',
    'CUC': 'Hydrophobic',
    'CUA': 'Hydrophobic',
    'CUG': 'Hydrophobic',
    'AUU': 'Hydrophobic',
    'AUC': 'Hydrophobic',
    'AUA': 'Hydrophobic',
    'AUG': 'Hydrophobic',
    # Positively Charged
    'CGU': 'Positively Charged',
    'CGC': 'Positively Charged',
    'CGA': 'Positively Charged',
    'CGG': 'Positively Charged',
    'AGA': 'Positively Charged',
    'AGG': 'Positively Charged',
    'AAA': 'Positively Charged',
    'AAG': 'Positively Charged',
    'CAU': 'Positively Charged',
    'CAC': 'Positively Charged',
    # Negatively Charged
    'GAU': 'Negatively Charged',
    'GAC': 'Negatively Charged',
    'GAA': 'Negatively Charged',
    'GAG': 'Negatively Charged',
    # Polar
    'UCU': 'Polar',
    'UCC': 'Polar',
    'UCA': 'Polar',
    'UCG': 'Polar',
    'AGU': 'Polar',
    'AGC': 'Polar',
    'AAU': 'Polar',
    'ACU': 'Polar',
    'ACC': 'Polar',
    'ACA': 'Polar',
    'ACG': 'Polar',
    'AAC': 'Polar',
    'CAA': 'Polar',
    'CAG': 'Polar',
    # Aromatic
    'UUU': 'Aromatic',
    'UUC': 'Aromatic',
    'UAU': 'Aromatic',
    'UAC': 'Aromatic',
    'UGG': 'Aromatic',
    # Special
    'UGU': 'Special',
    'UGC': 'Special',
    'GGU': 'Special',
    'GGC': 'Special',
    'GGA': 'Special',
    'GGG': 'Special',
    'CCU': 'Special',
    'CCC': 'Special',
    'CCA': 'Special',
    'CCG': 'Special',
    # Stop
    'UAA': 'Stop',
    'UAG': 'Stop',
    'UGA': 'Stop'
}
color_map = {
    'Hydrophobic': '#00FF00',         # 绿色 - 疏水氨基酸
    'Positively Charged': '#FF1493',  # 深粉色 - 带正电氨基酸
    'Negatively Charged': '#00BFFF',  # 深天蓝色 - 带负电氨基酸
    'Polar': '#FFA500',               # 橙色 - 极性氨基酸
    'Aromatic': '#FF0000',            # 金色 - 芳香族氨基酸
    'Special': '#800080',             # 紫色 - 特殊功能氨基酸
    'Stop': '#0000FF'                 # 蓝色 - 终止密码子
}

species_list = [
    'A.thaliana',
    'H.sapiens',
    'P.pastoris',
    'E.coli',
    'H.volcanii',
    'D.melanogaster',
    'S.cerevisiae'
]

species_color_map = {
    'A.thaliana':     '#E69F00',  # 橙黄（拟南芥，模式植物）
    'H.sapiens':      '#56B4E9',  # 天蓝（人类，灵长类代表）
    'P.pastoris':     '#009E73',  # 翡翠绿（毕赤酵母，工业微生物）
    'E.coli':         '#D55E00',  # 赭红色（大肠杆菌，原核模式生物）
    'H.volcanii':     '#CC79A7',  # 粉紫（盐古菌，极端环境微生物）
    'D.melanogaster': '#0072B2',  # 深蓝（果蝇，遗传学模式生物）
    'S.cerevisiae':   '#F0E442'   # 明黄（酿酒酵母，经典真核模型）
}

codon_to_aa = {
    'UUU':'F',
    'UUC': 'F',
    'UUA': 'L',
    'UUG': 'L',
    'CUU': 'L',
    'CUC': 'L',
    'CUA': 'L',
    'CUG': 'L',
    'AUU': 'I',
    'AUC': 'I',
    'AUA': 'I',
    'AUG': 'M',
    'GUU': 'V',
    'GUC': 'V',
    'GUA': 'V',
    'GUG': 'V',
    'UCU': 'S',
    'UCC': 'S',
    'UCA': 'S',
    'UCG': 'S',
    'AGU': 'S',
    'AGC': 'S',
    'CCU': 'P',
    'CCC': 'P',
    'CCA': 'P',
    'CCG': 'P',
    'ACU': 'T',
    'ACC': 'T',
    'ACA': 'T',
    'ACG': 'T',
    'GCU': 'A',
    'GCC': 'A',
    'GCA': 'A',
    'GCG': 'A',
    'UAU': 'Y',
    'UAC': 'Y',
    'UAA': '*',
    'UAG': '*',
    'UGA': '*',
    'CAU': 'H',
    'CAC': 'H',
    'CAA': 'Q',
    'CAG': 'Q',
    'AAU': 'N',
    'AAC': 'N',
    'AAA': 'K',
    'AAG': 'K',
    'GAU': 'D',
    'GAC': 'D',
    'GAA': 'E',
    'GAG': 'E',
    'UGU': 'C',
    'UGC': 'C',
    'UGG': 'W',
    'CGU': 'R',
    'CGC': 'R',
    'CGA': 'R',
    'CGG': 'R',
    'AGA': 'R',
    'AGG': 'R',
    'GGU': 'G',
    'GGC': 'G',
    'GGA': 'G',
    'GGG': 'G'
}

codon_to_aa_pretrain = {
    'UUU':'F',
    'UUC': 'F',
    'UUA': 'L',
    'UUG': 'L',
    'CUU': 'L',
    'CUC': 'L',
    'CUA': 'L',
    'CUG': 'L',
    'AUU': 'I',
    'AUC': 'I',
    'AUA': 'I',
    'AUG': 'M',
    'GUU': 'V',
    'GUC': 'V',
    'GUA': 'V',
    'GUG': 'V',
    'UCU': 'S',
    'UCC': 'S',
    'UCA': 'S',
    'UCG': 'S',
    'AGU': 'S',
    'AGC': 'S',
    'CCU': 'P',
    'CCC': 'P',
    'CCA': 'P',
    'CCG': 'P',
    'ACU': 'T',
    'ACC': 'T',
    'ACA': 'T',
    'ACG': 'T',
    'GCU': 'A',
    'GCC': 'A',
    'GCA': 'A',
    'GCG': 'A',
    'UAU': 'Y',
    'UAC': 'Y',
    'UAA': '.',#* for CodonTransformer
    'UAG': '.',
    'UGA': '.',
    'CAU': 'H',
    'CAC': 'H',
    'CAA': 'Q',
    'CAG': 'Q',
    'AAU': 'N',
    'AAC': 'N',
    'AAA': 'K',
    'AAG': 'K',
    'GAU': 'D',
    'GAC': 'D',
    'GAA': 'E',
    'GAG': 'E',
    'UGU': 'C',
    'UGC': 'C',
    'UGG': 'W',
    'CGU': 'R',
    'CGC': 'R',
    'CGA': 'R',
    'CGG': 'R',
    'AGA': 'R',
    'AGG': 'R',
    'GGU': 'G',
    'GGC': 'G',
    'GGA': 'G',
    'GGG': 'G'
}

codon_to_aa_finetune = {
    'UUU':'F',
    'UUC': 'F',
    'UUA': 'L',
    'UUG': 'L',
    'CUU': 'L',
    'CUC': 'L',
    'CUA': 'L',
    'CUG': 'L',
    'AUU': 'I',
    'AUC': 'I',
    'AUA': 'I',
    'AUG': 'M',
    'GUU': 'V',
    'GUC': 'V',
    'GUA': 'V',
    'GUG': 'V',
    'UCU': 'S',
    'UCC': 'S',
    'UCA': 'S',
    'UCG': 'S',
    'AGU': 'S',
    'AGC': 'S',
    'CCU': 'P',
    'CCC': 'P',
    'CCA': 'P',
    'CCG': 'P',
    'ACU': 'T',
    'ACC': 'T',
    'ACA': 'T',
    'ACG': 'T',
    'GCU': 'A',
    'GCC': 'A',
    'GCA': 'A',
    'GCG': 'A',
    'UAU': 'Y',
    'UAC': 'Y',
    'UAA': '*',#* for CodonTransformer
    'UAG': '*',
    'UGA': '*',
    'CAU': 'H',
    'CAC': 'H',
    'CAA': 'Q',
    'CAG': 'Q',
    'AAU': 'N',
    'AAC': 'N',
    'AAA': 'K',
    'AAG': 'K',
    'GAU': 'D',
    'GAC': 'D',
    'GAA': 'E',
    'GAG': 'E',
    'UGU': 'C',
    'UGC': 'C',
    'UGG': 'W',
    'CGU': 'R',
    'CGC': 'R',
    'CGA': 'R',
    'CGG': 'R',
    'AGA': 'R',
    'AGG': 'R',
    'GGU': 'G',
    'GGC': 'G',
    'GGA': 'G',
    'GGG': 'G'
}